service: bargain

plugins:
- serverless-python-requirements

custom:
  secrets: ${file(config/secrets.yml)}
  schedule: ${file(config/schedule.yml)}

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  timeout: 10

  stage: prod
  region: eu-west-1

  environment:
    BITFINEX_API_KEY: ${self:custom.secrets.exchanges.bitfinex.api_key}
    BITFINEX_API_SECRET: ${self:custom.secrets.exchanges.bitfinex.api_secret}

package:
  exclude:
  - '**'
  include:
  - bargain/**

functions:
  trade:
    handler: bargain/main.serverless_handler
    events: ${self:custom.schedule.trades}

  plot:
    handler: bargain/plots.serverless_handler
    timeout: 30
    environment:
      PLOTLY_USERNAME: ${self:custom.secrets.plotly.username}
      PLOTLY_API_KEY: ${self:custom.secrets.plotly.api_key}
    events:
    - name: bargain-plot
      rate: cron(0 * * * ? *)
