trades:
- schedule:
    name: bargain-ether
    rate: cron(1-59/5 * * * ? *)
    input:
      pair: [ETH, USD]
      interval: 5
      indicator:
        crossover:
          buy:  {alma: {length: 13, offset: 0.85, sigma: 6}}
          sell: {alma: {length: 49, offset: 0.85, sigma: 6}}
